# -*- coding: utf-8 -*-
"""login.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKZAvODDW3R3eqHQFSZYcQCwoBZJHFnF
"""

import hashlib
import os

# Dictionary to store user credentials
users = {}

def hash_password(password, salt):
    return hashlib.sha256(salt.encode() + password.encode()).hexdigest()

def sign_up():
    username = input("Choose a username: ")
    if username in users:
        print("❌ Username already exists. Try another.")
        return
    password = input("Create a password: ")
    salt = os.urandom(16).hex()  # Generate a random salt
    hashed_password = hash_password(password, salt)
    users[username] = {'salt': salt, 'password': hashed_password}
    print("✅ Account created successfully!\n")

def log_in():
    username = input("Enter your username: ")
    if username not in users:
        print("❌ Username not found. Sign up first!\n")
        return
    password = input("Enter your password: ")
    stored_salt = users[username]['salt']
    stored_hashed_password = users[username]['password']
    if hash_password(password, stored_salt) == stored_hashed_password:
        print("✅ Login successful!\n")
    else:
        print("❌ Incorrect password. Try again.\n")

def main():
    while True:
        print("\n1️⃣ Sign Up  |  2️⃣ Log In  |  3️⃣ Exit")
        choice = input("Choose an option (1/2/3): ")
        if choice == '1':
            sign_up()
        elif choice == '2':
            log_in()
        elif choice == '3':
            print("Goodbye! 👋")
            break
        else:
            print("❌ Invalid choice. Please enter 1, 2, or 3.\n")

if __name__ == "__main__":
    main()

